### PR TITLE
Add option to use __builtin_popcount.

### PR DESCRIPTION
**Pull request by grebe**

### CODE REVIEW

**Review by jdart1 — CHANGES_REQUESTED** [review]
__has_builtin is specific to GCC. IMO you should test for this, otherwise it will not compile under other compilers such as Visual C++. Code should read I think:
// try to use a builtin
#if defined (__has_builtin)
#if __has_builtin(__builtin_popcountll)
#define popcount(x) __builtin_popcountll((x))
#else
#define TB_SOFTWARE_POP_COUNT
#endif
#else
#define TB_SOFTWARE_POP_COUNT
#endif
#endif

**Comment by grebe** [comment]
Clang supports `__has_builtin`, so I forgot windows exists and might not support it :). From [here](https://clang.llvm.org/docs/LanguageExtensions.html), clang recommends starting off with

```
#ifndef __has_builtin
  #define __has_builtin(x)
#endif
```

I'm happy to do what you proposed instead, let me know which you prefer.

**Comment by jdart1** [comment]
I don't have a strong preference how this is fixed - the first solution is GCC's recommendation.

**Comment by jdart1** [comment]
Addressed in https://github.com/jdart1/Fathom/commit/c135b094eb8227a282bbfb4d01f8de7907b0a9e6.

**Pull request closed without merging**
